# Generated by Django 5.2.7 on 2026-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoEstadistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número / símbolo')),
                ('etiqueta', models.CharField(max_length=60, verbose_name='Etiqueta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': '8. Estadísticas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipoFinalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('categoria', models.CharField(choices=[('varonil_libre', 'Varonil Libre'), ('juvenil_mayor', 'Juvenil Mayor'), ('juvenil_menor', 'Juvenil Menor'), ('femenil', 'Femenil')], max_length=20, verbose_name='Categoría')),
                ('tipo', models.CharField(choices=[('liga_1', '🥇 Liga — 1er lugar'), ('liga_2', '🥈 Liga — 2do lugar'), ('copa_1', '🥇 Copa — 1er lugar'), ('copa_2', '🥈 Copa — 2do lugar'), ('consolacion_2', '🥈 Consolación — 2do lugar'), ('primer_lugar', '🥇 1er lugar'), ('segundo_lugar', '🥈 2do lugar'), ('mejor_portero', '🧤 Mejor Portero'), ('mejor_goleador', '⚽ Mejor Goleador')], max_length=20, verbose_name='Premio / lugar')),
                ('equipo', models.CharField(blank=True, max_length=100, verbose_name='Nombre del equipo o jugador (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Equipo / Premio Finalista',
                'verbose_name_plural': '5d. Finales de Torneo — Equipos y Premios',
                'ordering': ['categoria', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('badge', models.CharField(max_length=60, verbose_name='Etiqueta (emoji + texto)')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=220, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': '6. Eventos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FilosofiaSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto de Filosofía',
                'verbose_name_plural': '5. Filosofía — Carrusel',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoCampeonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es la foto grande?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto de Campeonas',
                'verbose_name_plural': '3. Campeonas — Fotos',
                'ordering': ['-es_principal', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': '4. Galería',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto del Inicio (Hero)',
                'verbose_name_plural': '1. Inicio — Carrusel principal',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='⚽', max_length=10, verbose_name='Icono (emoji)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('contenido_html', models.TextField(help_text='Se inserta tal cual dentro de la tarjeta, puedes usar <br/> y <strong>.', verbose_name='Contenido (admite <br/> y <strong>)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tarjeta de la Academia',
                'verbose_name_plural': '7. Academia — Tarjetas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='📱', max_length=10, verbose_name='Icono (emoji)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('detalle', models.CharField(max_length=200, verbose_name='Detalle')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Dato de contacto',
                'verbose_name_plural': '10. Contacto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='🏆', max_length=10, verbose_name='Icono (emoji)')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': '3. Campeonas — Logros',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto de Material de Entrenamiento',
                'verbose_name_plural': '5b. Materiales de Entrenamiento — Carrusel',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp / Teléfono')),
                ('categoria', models.CharField(blank=True, max_length=60, verbose_name='Categoría de interés')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Recibido')),
            ],
            options={
                'verbose_name': 'Mensaje recibido',
                'verbose_name_plural': '11. Mensajes de contacto',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(help_text='Ej: 🏆 Torneo Nacional', max_length=60, verbose_name='Categoría')),
                ('resumen', models.TextField(verbose_name='Resumen / Descripción')),
                ('fecha_texto', models.CharField(default='2026', max_length=40, verbose_name='Fecha (texto libre)')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('destacada', models.BooleanField(default=False, verbose_name='¿Es la noticia principal?')),
                ('enlace_seccion', models.CharField(default='academia', help_text='A qué sección del sitio enlaza esta tarjeta (sin #), ej: academia, campeonas, galeria', max_length=50, verbose_name='Enlace interno')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': '2. Noticias',
                'ordering': ['-destacada', 'orden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Puede ser una sola imagen con todos los logos, o subir varias filas.', upload_to='img/', verbose_name='Imagen (franja de logos o logo individual)')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': '5c. Patrocinadores',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': '5e. Publicidad — Flyers y Anuncios',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValorFilosofia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='⚽', max_length=10, verbose_name='Icono (emoji)')),
                ('texto', models.CharField(max_length=150, verbose_name='Texto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Valor',
                'verbose_name_plural': '5. Filosofía — Valores',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Guerreros CF en acción', max_length=150, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
                ('youtube_url', models.URLField(blank=True, help_text='Pega aquí el link del video ya subido a YouTube, ej: https://www.youtube.com/watch?v=XXXXXXXXXXX', verbose_name='Link de YouTube (recomendado)')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Archivo de video (alternativa, solo clips cortos < 100 MB)')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen de portada (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': '9. Video destacado',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
